# Generated by Django 4.2.23 on 2025-07-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoty',
            new_name='ProductCategory',
        ),
    ]
